In [3]:
# PACKAGE YANG DIGUNAKAN
# xlrd, numpy, pandas, seaborn

# IMPORT PACKAGE
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Dense, Flatten
from sklearn.compose import ColumnTransformer
from tensorflow.keras.models import Sequential
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [ ]:
# IMPORT DATASET
dataset = pd.read_excel("churndata.xlsx")

In [12]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [9]:
# SPLIT DATA TESTING AND TRAINING
x=dataset.iloc[:,3:13].values
y=dataset.iloc[:,-1].values

In [10]:
# DATA MASIH PERLU DIOLAH
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [11]:
# ENCODER LABEL & ONE HOT
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
le = LabelEncoder()
x[:,1] = le.fit_transform(x[:,1])
x[:,2] = le.fit_transform(x[:,2])
one = ColumnTransformer([("Geography", OneHotEncoder(), [1])], remainder = 'passthrough')
x = one.fit_transform(x)

NameError: name 'ColumnTransformer' is not defined

In [36]:
x.shape

(10000, 12)

In [37]:
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [38]:
# DATA SPLIT FOR MODELLING
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size= 0.4, random_state= 1234)

In [39]:
#Scaling Data
sc = StandardScaler()
X_train = sc.fit_transform(X_train)

In [40]:
X_test = sc.transform(X_test)

In [41]:
X_train.shape

(6000, 12)

In [42]:
X_test.shape

(4000, 12)

In [43]:
# MODELLING AND TRAINING
model = Sequential()
model.add(Dense(500, input_dim=12, activation='relu'))
model.add(Dense(300, activation='relu'))
model.add(Dense(200, activation='relu'))
model.add(Dense(200, activation='relu'))
model.add(Dense(200, activation='relu'))
model.add(Dense(200, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [44]:
# Compiling the ANN
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
model.fit(X_train, y_train, batch_size = 1000, epochs = 100,validation_data=(X_test,y_test))

Train on 6000 samples, validate on 4000 samples
Epoch 1/100
6000/6000 [==============================] - 5s 835us/sample - loss: 0.5753 - accuracy: 0.7740 - val_loss: 0.4984 - val_accuracy: 0.7962
Epoch 2/100
6000/6000 [==============================] - 0s 22us/sample - loss: 0.4674 - accuracy: 0.7963 - val_loss: 0.4444 - val_accuracy: 0.7962
Epoch 3/100
6000/6000 [==============================] - 0s 12us/sample - loss: 0.4316 - accuracy: 0.7963 - val_loss: 0.4302 - val_accuracy: 0.7962
Epoch 4/100
6000/6000 [==============================] - 0s 11us/sample - loss: 0.4166 - accuracy: 0.7963 - val_loss: 0.4240 - val_accuracy: 0.7962
Epoch 5/100
6000/6000 [==============================] - 0s 11us/sample - loss: 0.4007 - accuracy: 0.8088 - val_loss: 0.4048 - val_accuracy: 0.8325
Epoch 6/100
6000/6000 [==============================] - 0s 12us/sample - loss: 0.3764 - accuracy: 0.8502 - val_loss: 0.3813 - val_accuracy: 0.8495
Epoch 7/100
6000/6000 [==============================] - 0s 11u

Epoch 56/100
6000/6000 [==============================] - 0s 11us/sample - loss: 0.0419 - accuracy: 0.9850 - val_loss: 1.1727 - val_accuracy: 0.8175
Epoch 57/100
6000/6000 [==============================] - 0s 11us/sample - loss: 0.0334 - accuracy: 0.9890 - val_loss: 1.2310 - val_accuracy: 0.8170
Epoch 58/100
6000/6000 [==============================] - 0s 10us/sample - loss: 0.0295 - accuracy: 0.9882 - val_loss: 1.2229 - val_accuracy: 0.8248
Epoch 59/100
6000/6000 [==============================] - 0s 10us/sample - loss: 0.0346 - accuracy: 0.9870 - val_loss: 1.2849 - val_accuracy: 0.7995
Epoch 60/100
6000/6000 [==============================] - 0s 11us/sample - loss: 0.0348 - accuracy: 0.9873 - val_loss: 1.2794 - val_accuracy: 0.8253
Epoch 61/100
6000/6000 [==============================] - 0s 11us/sample - loss: 0.0336 - accuracy: 0.9895 - val_loss: 1.2810 - val_accuracy: 0.7883
Epoch 62/100
6000/6000 [==============================] - 0s 11us/sample - loss: 0.0437 - accuracy: 0.9827

In [45]:
model.save('model.h5')

In [47]:
# Predicting the Test set results
#if y_pred is larger than 0.5 it returns true(1) else false(2)
y_pred = model.predict(X_test)
y_pred_1 = (y_pred > 0.5)

In [48]:
# Creating the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred_1)

In [49]:
# Con
print(cm)

[[2845  340]
 [ 408  407]]
